#datapath : "/home/AD/c817h/Documents/data/data"
#logpath : "/home/AD/c817h/Documents/data/logs_cradl"

datapath : "/home/silvia/Documents/CRADL/pre-processed"
logpath : "/home/silvia/Documents/CRADL/logs_cradl"


