accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: true
benchmark: true
check_val_every_n_epoch: 1
checkpoint_callback: true
default_root_dir: null
deterministic: false
distributed_backend: null
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 1
gradient_clip_val: 0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: 100
max_steps: null
min_epochs: 1
min_steps: null
num_nodes: 1
num_processes: 1 # number of processes for distributed training
num_workers: 12
overfit_batches: 0.0
precision: 16
prepare_data_per_node: true
profiler: null
progress_bar_refresh_rate: 10
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
single_class: true
sync_batchnorm: false
terminate_on_nan: false
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 1.0
weights_save_path: null
weights_summary: top
